### ISSUE TITLE
Trying to install and run example gives error

### ISSUE THREAD

**Issue by mathDR** [sjwhitworth/golearn#107]
Apparently github.com/gonum/blas/cblas was recently changed to github.com/gonum/blas/cblas128  This, by the way breaks the go get -u -t ./... command

package github.com/sjwhitworth/golearn
	imports github.com/sjwhitworth/golearn/base
	imports github.com/gonum/blas
	imports github.com/gonum/blas/blas64
	imports github.com/gonum/blas/native
	imports github.com/gonum/internal/asm
	imports github.com/gonum/matrix/mat64
	imports github.com/smartystreets/goconvey/convey
	imports github.com/jtolds/gls
	imports github.com/smartystreets/goconvey/convey/assertions
	imports github.com/smartystreets/goconvey/convey/assertions/oglematchers
	imports github.com/smartystreets/goconvey/convey/gotest
	imports github.com/smartystreets/goconvey/convey/reporting
	imports github.com/sjwhitworth/golearn/ensemble
	imports github.com/gonum/blas/cblas
	imports github.com/gonum/blas/cblas
	imports github.com/gonum/blas/cblas: cannot find package "github.com/gonum/blas/cblas" in any of:
	/usr/local/Cellar/go/1.4/libexec/src/github.com/gonum/blas/cblas (from $GOROOT)
	/Users/mathDR/gocode/src/github.com/gonum/blas/cblas (from $GOPATH)

**Comment by Sentimentron** [comment]
This would also explain why Travis is broken.

**Comment by savorywatt** [comment]
Yeah I noticed that on my build, ahhh dependency management in go. If I
have time tonight I'll see if I can fix it

R

**Comment by sjwhitworth** [comment]
Have fixed this in a PR.

**Comment by Sentimentron** [comment]
Closed in #109.

**Comment by davmaz** [comment]
Hello -
  I've been trying to test matrix math in go(lang). I've got OpenBLAS installed and lapack and cgo. However, I don't have a simple main.go to test it with. Do you have any? It would really help getting started...
Thanks!
