### ISSUE TITLE
beginner: creating predict/test data 

### ISSUE THREAD

**Issue by sathishvj** [sjwhitworth/golearn#111]
Could you give me an example or an easy method to create the instances for test data?  I was able to follow the main example in the landing page to split train-test data of something similar to that below:

10,hello,hello
9,helow,hello
8,mahalo,mahalo
12,helo,hello
7,hallo,hello
5,halo,hello
11,hellow,hello
8,mhalo,mahalo
12,mehalo,mahalo

But how do I now create a test data instance of something like below that I can pass to a Predict function?
10,melo

Is there a way to add it in a way similar to ParseCSVToInstances?  Maybe a ParseStringToPredictInstance?  Or ParseCSVToPredictInstance?

**Comment by Sentimentron** [comment]
Hi @sathishvj, sorry it's taken a while to get back to you (I've been on holiday). 

Here's my recommendation: I imagine your code looks somewhat similar to the following, and you want to know how to construct `test`:
```
// Parse the CSV to a DenseInstances with headers
inst ,err := base.ParseCSVToInstances("train.csv", true)
if err != nil {
    panic(err);
}

// Do a train-test split
train, test = base.InstancesTrainTestSplit(src, 0.8);

// Train the classifier
cls.Fit(train)

// Print predictions
fmt.Println(cls.Predict(test))
``` 

You _can_ create `test` by using `NewDenseInstances`, using `AddAttributes` and then `Extend`, and then doing `GetSysValFromString` on the categories to retrieve the system values and then `Set` to store the bytes, _or_ you can put your data in a `test.csv` file and use `ParseCSVToTemplatedInstances`. In which case, the rough equivalent of the code above would be:

```
train, err := base.ParseCSVToInstances("train.csv", true)
if err != nil {
   panic(err);
}

// Load test data
test, err := base.ParseCSVToTemplatedInstances("test.csv", true, train);
if err != nil {
   panic(err);
}
...
```

Just make sure that your `test.csv` is in exactly the same format as the `train.csv` one, and it should work. If it doesn't, or you have more questions, feel free to comment and re-open this issue.
