### ISSUE TITLE
[knnclassifier] compiler error with Dot

### ISSUE THREAD

**Issue by EtienneBruines** [sjwhitworth/golearn#119]
Something broke example `knnclassifier`. I wasn't sure what the problem is (at first), as I was just getting started with this library. 

```
# github.com/sjwhitworth/golearn/metrics/pairwise
../../metrics/pairwise/euclidean.go:17: vectorX.Dot undefined (type *mat64.Dense has no field or method Dot)
../../metrics/pairwise/poly_kernel.go:21: vectorX.Dot undefined (type *mat64.Dense has no field or method Dot)
```

Problem seems to be in a breaking change in the `gonum/matrix` library. 
See https://github.com/gonum/matrix/commit/ef442ed5f2e6da03a1dbf42d164180071ab2c121

Working on a PR to fix.

**Comment by anzellai** [comment]
I have encountered the same error messages, and @EtienneBruines pull request does fix the issue.

**Comment by Sentimentron** [comment]
Excellent! Weill be merged shortly.
