### ISSUE TITLE
RF Predicting

### ISSUE THREAD

**Issue by kevinchapron** [sjwhitworth/golearn#153]
Hi Guys, I have a problem with your implementation of **RandomForest**.
I got two datasets. The training dataset has four classes , A, B, C, D. 
The second dataset (testing dataset) has A, B, or C, D, or B, C ... i tried everything.

My code for the training is the following : 

```
instances, err := base.ParseCSVToInstances(FILENAME_TRAINING_SHORT, true)
if err != nil {
	panic(err)
}

forest := ensemble.NewRandomForest(MJ.NUMBER_TREE,MJ.NUMBER_FEATURES)
err_training := forest.Fit(instances)
if err_training != nil {
	panic(err_training)
}
```

And for the testing : 

```
instances,` _ := base.ParseCSVToInstances(tmp_file,true)
predictions , _ := forest.Predict(instances)
print(predictions)
```

Aswell i would like to generate the testing dataset directly with data, without the need of CSV, but didn't find how to make it properly. Previous issue was opened to generate dataset with mat64, but theses do not contain headers ... 

By the way, my code is actually resulting in that error : 
```
panic: Error resolving Attribute CategoricalAttribute("Result", [A B C D]): Couldn't resolve CategoricalAttribute("Result", [A B C D])

goroutine 243 [running]:
panic(0x2faa50, 0x56fd00a0)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x330
github.com/sjwhitworth/golearn/base.ResolveAttributes(0x4635d0a0, 0x56fdf860, 0x56dc3280, 0x9, 0x10, 0x0, 0x0, 0x0)
        /home/kevin/go/src/github.com/sjwhitworth/golearn/base/util_attributes.go:48 +0x25c
github.com/sjwhitworth/golearn/base.NewInstancesViewFromAttrs(0x4635d158, 0x56fdf860, 0x56dc3280, 0x9, 0x10, 0x2cc740)
        /home/kevin/go/src/github.com/sjwhitworth/golearn/base/view.go:102 +0x64
github.com/sjwhitworth/golearn/meta.(*BaggedModel).generatePredictionInstances(0x57018bc0, 0x2, 0x4635d158, 0x56fdf860, 0x0, 0x0)
        /home/kevin/go/src/github.com/sjwhitworth/golearn/meta/bagging.go:62 +0x84
github.com/sjwhitworth/golearn/meta.(*BaggedModel).Predict.func2(0x56fdf950, 0x57018bc0, 0x4635d158, 0x56fdf860, 0x57196e00, 0x56d4be00)
        /home/kevin/go/src/github.com/sjwhitworth/golearn/meta/bagging.go:142 +0x98
created by github.com/sjwhitworth/golearn/meta.(*BaggedModel).Predict
        /home/kevin/go/src/github.com/sjwhitworth/golearn/meta/bagging.go:150 +0x18c
```

Thanks,
Kévin

**Comment by Sentimentron** [comment]
Hi Kévin, have you tried[ `base.ParseCSVToTemplatedInstances`](https://godoc.org/github.com/sjwhitworth/golearn/base#ParseCSVToTemplatedInstances)?

`instances, _ := base.ParseCSVToTemplatedInstances(tmp_file, true, trainingData)
predictions , _ := forest.Predict(instances)
print(predictions)`

**Comment by kevinchapron** [comment]
Thanks a lot, it solved the problem !

wouldn't it be more cool if "Bagging" class had an other method to return predictions slices ?
A method exactly like Predict, but returning all voting instead of max voting class ?

It could be great to know if most voted prediction was really beyond the others
I'll do it for myself with a fork of your project, but i think it could be something to add in your lib !

Thanks again !
