### ISSUE TITLE
kdtree for knn

### ISSUE THREAD

**Issue by FrozenKP** [sjwhitworth/golearn#165]
I want to add kdtree to knn, where should I put kdtree.go ?

**Comment by Sentimentron** [comment]
Wherever you feel it's best suited. Perhaps in a new top-level directory called `kdtree` or something, because a decent kd-tree implementation is useful for clustering and all sorts of other things, but even if you kept inside `knn` we could always move it around.

**Comment by FrozenKP** [comment]
got it. thank a lot.
