### ISSUE TITLE
Chinese doc

### ISSUE THREAD

**Issue by FrozenKP** [sjwhitworth/golearn#166]
@jeasonstudio 

I want to help you translate golearn into Chinese. But I can only type Traditional Chinese, should I type Traditional Chinese directly to your doc ? 

or open a new directory named zh_tw and move your files to zh_cn ?

I think that Traditional Chinese may confused some people using Simplified Chinese....

**Comment by jeasonstudio** [comment]
It's ok.
You can open a new dir named zh_tw, I think this will be better.
很不錯的想法，希望能幫到在 golang 機器學習方面，幫到中國開發者，不論是用簡體還是繁體中文。

**Comment by FrozenKP** [comment]
Thanks a lot.
