### ISSUE TITLE
Signal kill 

### ISSUE THREAD

**Issue by SwanSpouse** [sjwhitworth/golearn#180]
when i run any test function in the project, it occurred "Signal kill"

Can you help me ?

**Comment by FrozenKP** [comment]
hi, can you give me more details ?

**Comment by Danzabar** [comment]
SwanSpouse - What operating system are you using? There was an update in OSX that caused this issue for me with various go packages. If it is OSx you are using you can use the flags `-ldflags -s` to get around this, ie `go test -ldflags -s`

**Comment by SwanSpouse** [comment]
@Danzabar thx, that's the problem.
