### ISSUE TITLE
Question: Possible to return more than 1 classification result?

### ISSUE THREAD

**Issue by meirwah** [sjwhitworth/golearn#185]
I'm using trees, after I trained my model (fit).
Im' trying to classify a single row, on 1 categorical attribute (Predict), then I will :
``` predictions.RowString(1) ``` to get the actual value that I'm looking for.

My question is, if i want to get several results ? ordered by Accuracy level?

For instance get 3 results, first result with highest probability, 2 result lower , 3 lower probability...

**Comment by meirwah** [comment]
Basically i'm looking for method: ```predict_proba()```
as described in: 
http://scikit-learn.org/stable/modules/tree.html#classification

**Comment by Sentimentron** [comment]
That's not something that's supported at the moment, it should be fairly
easy to adapt the existing Predict[1] function to make it work though

[1] https://github.com/Sentimentron/golearn/blob/master/trees/id3.go#L222

**Comment by meirwah** [comment]
can you give me some example for that?
some pointers?

on ID3DecisionTree maybe?
