### ISSUE TITLE
Dumping a tree

### ISSUE THREAD

**Issue by Nazariglez** [sjwhitworth/golearn#187]
Hi guys!

I'm new in the world of machine learning, and i'm trying to do some simple things with golearn. By now i'm using random tree to make a prediction, and it's works really well!, but if i use a really big dataset (10mb or so...) the time training is too high. So every time i start my app it's takes a lot of time training the tree.

I don't know if it's even possible, but I'm looking for a method to dump all the tree in a file or a database, and load later in "production" mode. 

Thanks!

**Comment by Sentimentron** [comment]
It's actually a feature I never got round to implementing, but it's a common problem so [I came up with a proposal for it](https://docs.google.com/document/d/1jn7Gx_81hB14IVvrG7d3h4D6Emg7jzjx6npazfM9jjA/edit?usp=sharing). Feel free to comment and it should be implemented in the next week or so.

**Comment by dreaminglwj** [comment]
您好，您的邮件已收到，我会尽快查看，^_^
