### ISSUE TITLE
Parse csv as a stream

### ISSUE THREAD

**Issue by EtienneBruines** [sjwhitworth/golearn#192]
Hi,

I've noticed that methods such as `base.ParseCSVToInstances`, do not have a `io.Reader` counterpart (it requires a `filename`). 

Would this be desirable? I personally would love the idea of just generating the csv in-memory (e.g. `bytes.Buffer`) and letting `golearn` figure out how to correctly parse it into instances -- without having to go in-depth into how that happens. 

Instead, the current implementation requires a `filename`, and repeatedly opens and reads that file. What about having additional methods that take an `io.Reader` (or something within `io` that specifies what we need/use), instead of solely requiring a filename? This would allow 

There is `base.ParseCSVBuildInstancesFromReader`, but have you seen the code needed to get it running? 

- [x] ParseCSVGetRows
- [x] ParseCSVGetAttributes
- [x] ParseCSVSniffAttributeTypes
- [x] ParseCSVSniffAttributeNames

Thoughts?

(I'll probably be implementing this anyway; so the question for me is whether I do it as part of `golearn`, of as part of the project I'm working on)

Thanks,
Etienne

**Comment by Sentimentron** [comment]
These are good thoughts, one thing that may be helpful is to do a version of `base.ParseCSVToTemplatedInstances`, where you build a `base.DenseInstances` by adding attributes and then reading your CSV data to that structure. We could also create new versions of ParseCSVGetRows etc to accept an `io.ReadSeeker` or similar. Do either of those options sound appealing?

**Comment by EtienneBruines** [comment]
@Sentimentron my apologies for getting back to you so late. The project was put on temporary hold, and has now continued. 

Right now, I have done the entire `csv.go` file, as a `Reader`. The methods exposed are still the same (for backwards compatibility), but all methods now internally use the `FromReader` counterpart. All existing tests pass. 

> We could also create new versions of `ParseCSVGetRows` etc to accept an `io.ReadSeeker` or similar. Do either of those options sound appealing?

That did indeed sound appealing. Not because it's the best solution overall (not sure if it is), but because it's the easiest to implement. (Without domain-knowledge, that is)
