### ISSUE TITLE
Feature Request: IsolationForest

### ISSUE THREAD

**Issue by DaGuich** [sjwhitworth/golearn#195]
I'd really like to see the IsolationForest in golearn. The IsolationForest is a outlier detection algorithm as described in [Isolation Forest (Fei Tony Liu, Kai Ming Ting, Zhi-Hua Zhou)](https://cs.nju.edu.cn/zhouzh/zhouzh.files/publication/icdm08b.pdf). It is also supported by pythons scikit-learn ([IsolationForest in scikit-learn](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.IsolationForest.html#sklearn.ensemble.IsolationForest))

**Comment by Sentimentron** [comment]
It looks reasonably simple to implement, depending on whether we could some good test cases for it.
