### ISSUE TITLE
Panics in library

### ISSUE THREAD

**Issue by amclay** [sjwhitworth/golearn#198]
Panics should not be part of a library. They cause unnecessary core dumps, and quit the parent process, which can be dangerous if used in production. There's several places where errors could be bubbled up, but are instead caught by panics

**Comment by Sentimentron** [comment]
It's a problem, sure, but not having to pass and check for an error within every function is also a bit cumbersome. Perhaps adding `panic`, `recover` around the affected exported API functions might work?

**Comment by sminez** [comment]
To be fair, passing and explicitly handling errors is the idiomatic go way of doing things. If the alternative is to always try to catch any panics that occur then it is a _lot_ easier to just check an error!

**Comment by kaustubhmallik** [comment]
Is the thing still relevant, if so, I would like to pick it.
