### ISSUE TITLE
how to save model and load model？

### ISSUE THREAD

**Issue by Mddct** [sjwhitworth/golearn#213]
how to save model and load model？

**Comment by Sentimentron** [comment]
Once you've created a model `cls` via `Fit` (see https://github.com/sjwhitworth/golearn/blob/master/examples/knnclassifier/knnclassifier_iris.go for an example), in most cases you can use `cls.Save(/path/to/file)` to save the classifier and use `cls.Load(/path/to/file)` to load it again. Both functions return an `error` if something went wrong.

Hope that helps! Feel free to re-open this issue if you have some further questions.
