### ISSUE TITLE
stat.CovarianceMatrix(nil, X_yk, nil) used as value？

### ISSUE THREAD

**Issue by luojh2015** [sjwhitworth/golearn#229]
https://github.com/sjwhitworth/golearn/blob/82e59c89f5020c45292c68472908f2150a87422e/clustering/em.go#L150

**Comment by luojh2015** [comment]
func CovarianceMatrix(dst *mat.SymDense, x mat.Matrix, weights []float64) {

**Comment by malsing** [comment]
I am also facing this issue and am quite confused!
