### ISSUE TITLE
Cross compile for ARMv7

### ISSUE THREAD

**Issue by lecndav** [sjwhitworth/golearn#244]
Hi,

is it possible to compile a program with e.g. random forest classification for ARM architectures?

**Comment by debugaftercoffee** [comment]
@lecndav Did you get this library working on ARM?

**Comment by lecndav** [comment]
@debugaftercoffee Yes, got it running on a raspberry pi

**Comment by debugaftercoffee** [comment]
@lecndav Can you share how you got it to cross compile? I'm on Mac trying to build for ARM. When I try to cross compile for ARM or set `CGO_ENABLE=0` I get the error associated with [270](https://github.com/sjwhitworth/golearn/issues/270). From what I can tell  the first reference to a C reference causes the build to fail. Any pointers you have would be greatly appreciated.

**Comment by lecndav** [comment]
@debugaftercoffee The main problem, I think, was with OpenBLAS. I had to install Fortran and needed to compile a lot packages and dependencies manually. But I can't remember the details. It was not suitable for me because the performance was bad.
