### ISSUE TITLE
Implement linear regression

### ISSUE THREAD

**Issue by sjwhitworth** [sjwhitworth/golearn#9]

**Comment by leifg** [comment]
What's the status of this? Has it been implemented in the meanwhile?

**Comment by njern** [comment]
This is implemented in the `linear` package

**Comment by lazywei** [comment]
In fact, I implemented [liblinear](https://github.com/lazywei/liblinear), the Golang wrapper of LIBLINEAR (C library) already. Please feel free to initiate the integration. :+1:
